apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: psp-zero
  name: psp:zero
rules:
- apiGroups:
  - policy
  resourceNames:
  - 00-zero
  resources:
  - podsecuritypolicies
  verbs:
  - use

